### ISSUE TITLE
Failed run of `gradlew runJs` because `file not present`

### ISSUE THREAD

**Issue by TobseF** [korlibs/korge-hello-world#1]
On Windows  `gradlew runJs` doesn't work because of a missing file. Maybe it searches in the wrong directory? What works like a charm is `runJvm` or `jsWeb`. 
Of course I can handle this by starting my own webserver inside the `\build\web`.

```
Caused by: net.rubygrapefruit.platform.NativeException: Could not start 'open'
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:27)
	at net.rubygrapefruit.platform.internal.WindowsProcessLauncher.start(WindowsProcessLauncher.java:22)
	at net.rubygrapefruit.platform.internal.WrapperProcessLauncher.start(WrapperProcessLauncher.java:36)
	at org.gradle.process.internal.ExecHandleRunner.startProcess(ExecHandleRunner.java:97)
	at org.gradle.process.internal.ExecHandleRunner.run(ExecHandleRunner.java:70)
	... 4 more
Caused by: java.io.IOException: Cannot run program "open" (in directory "D:\projects\Games\korge-hello-world-master"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	at net.rubygrapefruit.platform.internal.DefaultProcessLauncher.start(DefaultProcessLauncher.java:25)
	... 8 more
Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
	... 9 more
```
[Full Stacktrace](https://github.com/korlibs/korge-hello-world/files/2862684/Stacktrace.txt)

**Comment by soywiz** [comment]
Thanks for the report.

I used `open` To open the url to the web server. In windows i should use `explorer.exe`. That should be easy to fix. The jsRun task was added in korge 1.1.0. I will fix this in the next patch version.
